# Generated by Django 4.0.6 on 2022-07-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='city',
        ),
    ]
