# Generated by Django 4.0.6 on 2022-07-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='sr_no',
        ),
    ]
