# Generated by Django 4.0.6 on 2022-07-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_rename_id_customer_sr_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sr_no',
            new_name='id',
        ),
    ]
