# Generated by Django 4.0.6 on 2022-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_rename_econtact_employee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
